language: python
python:
  - "3.3"
  - "3.4"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y taglib1-dev
install: pip install -r requirements.txt
script:  python -m downspout.test.runtests
notifications:
  irc: "irc.freenode.org#downspout"
  template:
    - "%{repository}@%{branch}: %{message} (%{build_url})"
  on_success: change
  on_failure: change
  email:
    - ajduncan@gmail.com