language: python
python:
  - "3.3"
  - "3.4"
before_install:
  - sudo add-apt-repository ppa:kubuntu-ppa/backports -y
  - sudo apt-get update -q
  - sudo apt-get install -y libtag1-dev
install: pip install -r requirements.txt
script:  python -m tests.runtests
notifications:
  irc: "irc.freenode.org#downspout"
  template:
    - "%{repository}@%{branch}: %{message} (%{build_url})"
  on_success: change
  on_failure: change
  email:
    - ajduncan@gmail.com